
name: Deploy App Engine

on:
  pull_request:
    types:
      - closed
jobs:
  - id: 'auth'
  uses: 'google-github-actions/auth@v1'
  with:
    workload_identity_provider: 'projects/830746747943/locations/global/workloadIdentityPools/github-wif-pool/*'
    service_account: '  '


  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to App Engine. 
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        project_id: ${{secrets.PROYECT_ID}}


        
        