
name: Deploy App Engine

on:
  pull_request:
    types:
      - closed
jobs:

  auth:
    runs-on: ubuntu-latest 
    steps: 
      - uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{secret.WORKLOAD}}
          service_account: ${{secret.service_account}}

  if_merged:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
    - name: Deploy to App Engine. 
      id: deploy
      uses: google-github-actions/deploy-appengine@v0.2.0
      with:
        project_id: ${{secrets.PROYECT_ID}}


        
        